"""empty message

Revision ID: 1912220d6b7e
Revises: 48fbbb770c17
Create Date: 2019-03-30 16:55:34.699826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1912220d6b7e'
down_revision = '48fbbb770c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_post_event_id_event'), 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_event_id_event'), type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
