"""empty message

Revision ID: 48fbbb770c17
Revises: 
Create Date: 2019-03-30 16:55:21.274472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fbbb770c17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_author_slug'), ['slug'])

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_issue_slug'), ['slug'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_media_filename'), ['filename'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_media_filename'), type_='unique')

    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_issue_slug'), type_='unique')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_author_slug'), type_='unique')

    # ### end Alembic commands ###
