"""empty message

Revision ID: 66404ea43fa2
Revises: d84cffae5777
Create Date: 2019-04-13 19:17:38.895939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66404ea43fa2'
down_revision = 'd84cffae5777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_time', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('ignore_time')

    # ### end Alembic commands ###
